[workspace]
channels = ["conda-forge"]
name = "IsaacLab"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[system-requirements]
libc = "2.35"


[dependencies]
python = "3.10.*"
pip = ">=25.1.1,<26"

[pypi-dependencies]
torch = {version = ">=2.5.1, <3", index = "https://download.pytorch.org/whl/cu121"}
torchvision = {version = ">=0.20.1, <0.23", index = "https://download.pytorch.org/whl/cu121"}
isaacsim = { version = ">=4.5.0.0, <5", index = "https://pypi.nvidia.com", extras = ["all","extscache"] }

